set -g @plugin 'tmux-plugins/tpm'

# set -g @plugin 'tmux-plugins/tmux-yank'

# Plugin config

# Mouse
# set -g @better-mouse-scroll-on-drag false
# set -g @better-mouse-no-scroll-on-copy true

run '~/.tmux/plugins/tpm/tpm'
