set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-yank'

set-option -g default-command "reattach-to-user-namespace -l $SHELL"
set -g @yank_action 'copy-pipe'

run '~/.tmux/plugins/tpm/tpm'
