# General settings
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-255color:RGB"
set-option -g detach-on-destroy off
set -gq allow-passthrough on
set -g visual-activity off
set-option -g set-clipboard on

# Scroll
set -g history-limit 10000
set -g @scroll-speed-num-lines-per-scroll 1

# Start indexing from 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g mouse on  # Enable mouse
set-option -sg escape-time 10
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

set -g status-position top

# Dim inactive panes
set -g window-style 'fg=colour245,bg=colour236'
set -g window-active-style 'fg=default,bg=default'

# Theme — uncomment one to activate
source-file ~/.config/tmux/themes/gruvbox.conf
