local M = {}

M = {
	ignore_filetypes = {
		"help",
		"alpha",
		"dashboard",
		"lazy",
		"mason",
		"notify",
		"toggleterm",
		"netrw",
		"tutor",
		"NeogitStatus",
		"NeogitPopup",
		"DiffviewFiles",
	},
	icons = {
		diagnostics = {
			{ name = "DiagnosticSignError", text = "" },
			{ name = "DiagnosticSignWarn", text = "" },
			{ name = "DiagnosticSignHint", text = "" },
			{ name = "DiagnosticSignInfo", text = "" },
		},
		kind = {
			Array = " 󰅪 ",
			BlockMappingPair = " 󰅩 ",
			Boolean = "  ",
			BreakStatement = " 󰙧 ",
			Call = " 󰃷 ",
			CaseStatement = " 󰨚 ",
			Class = "  ",
			Color = "  ",
			Constant = "  ",
			Constructor = " 󰆧 ",
			ContinueStatement = "  ",
			Copilot = "  ",
			Declaration = " 󰙠 ",
			Delete = " 󰩺 ",
			DoStatement = " 󰑖 ",
			Element = " 󰅩 ",
			Enum = "  ",
			EnumMember = "  ",
			Event = "  ",
			Field = "  ",
			File = "  ",
			Folder = "  ",
			ForStatement = "󰑖 ",
			Function = " 󰆧 ",
			GotoStatement = " 󰁔 ",
			Identifier = " 󰀫 ",
			IfStatement = " 󰇉 ",
			Interface = "  ",
			Keyword = "  ",
			List = " 󰅪 ",
			Log = " 󰦪 ",
			Lsp = "  ",
			Macro = " 󰁌 ",
			MarkdownH1 = " 󰉫 ",
			MarkdownH2 = " 󰉬 ",
			MarkdownH3 = " 󰉭 ",
			MarkdownH4 = " 󰉮 ",
			MarkdownH5 = " 󰉯 ",
			MarkdownH6 = " 󰉰 ",
			Method = " 󰆧 ",
			Module = " 󰅩 ",
			Namespace = " 󰅩 ",
			Null = " 󰢤 ",
			Number = " 󰎠 ",
			Object = " 󰅩 ",
			Operator = "  ",
			Package = " 󰆧 ",
			Pair = " 󰅪 ",
			Property = "  ",
			Reference = "  ",
			Regex = "  ",
			Repeat = " 󰑖 ",
			Return = " 󰌑 ",
			RuleSet = " 󰅩 ",
			Scope = " 󰅩 ",
			Section = " 󰅩 ",
			Snippet = "  ",
			Specifier = " 󰦪 ",
			Statement = " 󰅩 ",
			String = "  ",
			Struct = "  ",
			SwitchStatement = " 󰨙 ",
			Table = " 󰅩 ",
			Terminal = "  ",
			Text = " 󰀬 ",
			Type = "  ",
			TypeParameter = "  ",
			Unit = "  ",
			Value = "  ",
			Variable = "  ",
			WhileStatement = " 󰑖 ",
		},
	},
}

return M
