local M = {}

M = {
	ignore_filetypes = {
		"help",
		"alpha",
		"dashboard",
		"lazy",
		"mason",
		"notify",
		"toggleterm",
		"netrw",
		"tutor",
		"NeogitStatus",
		"NeogitPopup",
		"DiffviewFiles",
	},
	icons = {
		diagnostics = {
			{ name = "DiagnosticSignError", text = "" },
			{ name = "DiagnosticSignWarn", text = "" },
			{ name = "DiagnosticSignHint", text = "" },
			{ name = "DiagnosticSignInfo", text = "" },
		},
		lsp = {
			File = "󰈙 ",
			Module = "󰆧 ",
			Namespace = "󰌗 ",
			Package = "󰏖 ",
			Class = "󰌗 ",
			Method = "󰆧 ",
			Property = "󰜢 ",
			Field = "󰜢 ",
			Constructor = "󰆧 ",
			Enum = "󰕘 ",
			Interface = "󰕘 ",
			Function = "󰊕 ",
			Variable = "󰀫 ",
			Constant = "󰏿 ",
			String = "󰀬 ",
			Number = "󰎠 ",
			Boolean = "◩ ",
			Array = "󰅪 ",
			Object = "󰅩 ",
			Key = "󰌋 ",
			Null = "󰟢 ",
			EnumMember = "󰕘 ",
			Struct = "󰌗 ",
			Event = "󰉁 ",
			Operator = "󰆕 ",
			TypeParameter = "󰊄 ",
		},
	},
}

return M
